[[section-system-scope-and-context]]
// == System Scope and Context
== Systeem Scope en Context


[role="arc42help"]
****
// .Contents
.Inhoud
// System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
// (neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.
De systeem scope en context maakt - zoals de naam suggereert - een onderscheid tussen het eigen systeem (d.w.z. de scope van het systeem dat wordt beschreven) en alle partners waarmee wordt gecommuniceerd (buur systemen en gebruikers, met andere woorden, de context van het systeem).
Hiermee worden externe interfaces gedefineerd.

// If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).
Maak, als het nodig is, onderscheid tussen business context (domein specifieke inputs en outputs) en technische context (kanalen, protocollen, hardware).

// .Motivation
.Motivatie
// The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. 
De domein en technische interfaces met communicatie partners horen bij meest kritieke aspecten van het systeem.
// Make sure that you completely understand them.
Wees er zeker van dat deze volledig te doorgronden.

// .Form
.Vorm
// Various options:
Verschillend opties:

// * Context diagrams
* Context diagrammen
// * Lists of communication partners and their interfaces.
* Lijst van communicatie partners en bijbehorende interfaces.


// .Further Information
.Verdere Informatie

// See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.
Zie https://docs.arc42.org/section-3/[Context en Scope] in de arc42 documentatie.

****


=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

****

**<Diagram or Table>**

**<optionally: Explanation of external domain interfaces>**

=== Technical Context

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

**<Diagram or Table>**

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**
